project_name: Erfrp

builds:
  - binary: frps
    main: ./frps.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm

    flags:
      - -trimpath
    ldflags:
      - -s -w

  - binary: frpc
    main: ./frpc.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm

    flags:
      - -trimpath
    ldflags:
      - -s -w


changelog:
  sort: asc
  filters:
    exclude:
      - '^chore'
      - '^tests'
      - '^ci'